### ISSUE TITLE
Python3 compatibility issue in django-libs test suite

### ISSUE THREAD

**Issue by BobBowles** [bitmazk/django-calendarium#38]
This isn't directly a problem in django-calendarium, but I am flagging it here because it affects running the test suite. 

I fixed another problem to do with PEP3114 in the test program, but when I re-ran the test I got this traceback:

    Test if ``OccurrenceForm`` is valid and saves correctly. ... ERROR
    
    ======================================================================
    ERROR: test_form (calendarium.tests.forms_tests.OccurrenceFormTestCase)
    Test if ``OccurrenceForm`` is valid and saves correctly.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/bob/WebProjects/django-calendarium-dev/calendarium/tests/forms_tests.py", line 36, in setUp
        created_by=UserFactory(),
      File "/home/bob/.virtualenvs/calendarium-py34-dj18/lib/python3.4/site-packages/factory/base.py", line 81, in __call__
        return cls.create(**kwargs)
      File "/home/bob/.virtualenvs/calendarium-py34-dj18/lib/python3.4/site-packages/factory/base.py", line 558, in create
        attrs = cls.attributes(create=True, extra=kwargs)
      File "/home/bob/.virtualenvs/calendarium-py34-dj18/lib/python3.4/site-packages/factory/base.py", line 400, in attributes
        force_sequence=force_sequence,
      File "/home/bob/.virtualenvs/calendarium-py34-dj18/lib/python3.4/site-packages/factory/containers.py", line 228, in build
        return stub.__fill__()
      File "/home/bob/.virtualenvs/calendarium-py34-dj18/lib/python3.4/site-packages/factory/containers.py", line 83, in __fill__
        res[attr] = getattr(self, attr)
      File "/home/bob/.virtualenvs/calendarium-py34-dj18/lib/python3.4/site-packages/factory/containers.py", line 105, in __getattr__
        val = val.evaluate(self, self.__containers)
      File "/home/bob/.virtualenvs/calendarium-py34-dj18/lib/python3.4/site-packages/factory/containers.py", line 160, in evaluate
        containers=containers,
      File "/home/bob/.virtualenvs/calendarium-py34-dj18/lib/python3.4/site-packages/factory/declarations.py", line 198, in evaluate
        return self.function(self.type(sequence))
      File "/home/bob/.virtualenvs/calendarium-py34-dj18/lib/python3.4/site-packages/django_libs/tests/factories.py", line 78, in <lambda>
        username = factory.Sequence(lambda n: md5(str(n)).hexdigest()[0:30])
    TypeError: Unicode-objects must be encoded before hashing
    
    ----------------------------------------------------------------------
    Ran 1 test in 0.010s
    
    FAILED (errors=1)

The error appears to come from django-libs. It does not happen running under python2.7, and I suspect it has to do with differences between python2 and python3 handling of unicode.

I tried seeing if there was an update for django-libs, but the version in use is already the latest.

I am not sure what to do here. I have the fix for the original problem checked into my py34-dj18 branch, but there seems no point in giving you a pull request until I know you can test it properly.

Can you look at this in django-libs? It looks as simple as adding `.encode('utf8')` to the string in the lambda, but I am not sure how that will play with python2.

**Comment by Tyrdall** [comment]
@BobBowles Seems so. Anyway, we've switched to mixer (https://github.com/klen/mixer) to create fixtures in newer projects, so I guess it doesn't make sense to fix the ``UserFactory``.

I added a fix, which replaces the use of ``UserFactory``: https://github.com/bitmazk/django-calendarium/commit/462694273608544a5aa37aceb6a5bc766efe8557
Unfortunately I don't have the time to remove factory boy completely =(
