### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by SaeX** [bitmazk/django-calendarium#45]
I'm getting `ImportError: No module named calendariumutils`:

	Traceback (most recent call last):
	  File "<snip>/manage.py", line 10, in <module>
		execute_from_command_line(sys.argv)
	  File "C:\test\lib\site-packages\django\core\management\__init__.py", line 338, in execute_from_command_line
		utility.execute()
	  File "C:\test\lib\site-packages\django\core\management\__init__.py", line 312, in execute
		django.setup()
	  File "C:\test\lib\site-packages\django\__init__.py", line 18, in setup
		apps.populate(settings.INSTALLED_APPS)
	  File "C:\test\lib\site-packages\django\apps\registry.py", line 85, in populate
		app_config = AppConfig.create(entry)
	  File "C:\test\lib\site-packages\django\apps\config.py", line 86, in create
		module = import_module(entry)
	  File "C:\Python27\Lib\importlib\__init__.py", line 37, in import_module
		__import__(name)
	ImportError: No module named calendariumutils

	Process finished with exit code 1

Any idea what this is due to? Where is the `calendariumutils` requirement coming from?
I tried to install as per the docs (https://django-calendarium.readthedocs.org/en/latest/installation.html).

Using 1.3.1 with Django 1.8.

Thanks!

**Comment by SaeX** [comment]
My bad, forgot a comma in the installed_apps... *sigh*

**Comment by Tyrdall** [comment]
;)
